# Generated by Django 5.1.1 on 2024-09-21 14:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_active_post_user_id_favorite_post_favorited_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user_id', 'post_id')},
        ),
    ]
