# Generated by Django 5.1.1 on 2024-09-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at']},
        ),
    ]
