# Generated by Django 5.1.1 on 2024-09-22 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_favorited_by_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favorited_by',
        ),
    ]
