# Generated by Django 5.1.1 on 2024-10-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_post_referenceactive_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='liked_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
