# Generated by Django 5.1.1 on 2024-11-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_post_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
