# Generated by Django 5.1.1 on 2024-11-22 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_history_is_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='favorited_at',
        ),
    ]
