# Generated by Django 5.1.1 on 2024-11-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_remove_history_favorited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
