# Generated by Django 5.1.1 on 2024-11-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_history_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentChecked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='referenceChecked',
            field=models.BooleanField(default=False),
        ),
    ]
