# Generated by Django 5.1.1 on 2024-11-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_reported_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reported',
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
