# Generated by Django 5.1.1 on 2024-11-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lang',
        ),
    ]
